greeting:
  message: "hello"
quarkus:
  quinoa:
    package-manager: "pnpm"
    package-manager-command:
      dev: "run dev"
    enable-spa-routing: true
    build-dir: "dist"
    dev-server:
      port: 5173
